ProductOperation.Web/Models/ErrorViewModel.cs
namespace ProductOperation.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ProductOperation.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using ProductOperation.Core.DTOs;
using ProductOperation.Core.Services;

namespace ProductOperation.Web.Controllers
{
    public class HomeController : Controller
    {
        IProductionOperationService productionService;

        public HomeController(IProductionOperationService productionService)
        {
            this.productionService=productionService;
        }

        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Index(DateTime dateTime)
        {
            ViewBag.Message = dateTime.ToString("dd/MM/yyyy");
            List<ProductionOperationDTO> products = productionService.Reorganize(dateTime);
            return View(products);
        }

    }
}

ProductOperation.Web/Controllers/ProductionOperationController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using ProductOperation.Core.DTOs;
using ProductOperation.Core.Models;
using ProductOperation.Core.Services;

namespace ProductOperation.Web.Controllers
{
    public class ProductionOperationController : Controller
    {
        private readonly IProductionOperationService _service;

        private readonly IMapper _mapper;

        public ProductionOperationController(IProductionOperationService productOperationService, IMapper mapper)
        {
            this._service=productOperationService;
            _mapper=mapper;
        }

        public async Task<IActionResult> Index()
        {
            List<ProductionOperation> pos = _service.GetAll().Where(p => p.StartDateTime.Date == new DateTime(2020, 05, 23).Date).ToList();
            List<ProductionOperationDTO> productOperationDTOs = _mapper.Map<List<ProductionOperationDTO>>(pos);
            foreach (ProductionOperationDTO productOperationDTO in productOperationDTOs)
            {
                TimeSpan dateTime = productOperationDTO.EndDateTime-(productOperationDTO.StartDateTime);
                productOperationDTO.TotalTime = dateTime;
            }
            return View(productOperationDTOs);
        }
        [HttpPost]
        public IActionResult Index(DateTime dateTime)
        {
            List<ProductionOperation> pos = _service.GetAll().Where(p => p.StartDateTime.Date == dateTime.Date).ToList();
            List<ProductionOperationDTO> productOperationDTOs = _mapper.Map<List<ProductionOperationDTO>>(pos);
            foreach (ProductionOperationDTO productOperationDTO in productOperationDTOs)
            {
                TimeSpan tdaTime = productOperationDTO.EndDateTime-(productOperationDTO.StartDateTime);
                productOperationDTO.TotalTime = tdaTime;
            }
            return View(productOperationDTOs);
        }
        public IActionResult Save()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Save(ProductionOperationDTO operationDTO)
        {
            if (ModelState.IsValid)
            {
                ProductionOperation production = _mapper.Map<ProductionOperation>(operationDTO);
                await _service.AddAsync(production);
                return RedirectToAction(nameof(Index));
            }
            return View();
        }
        public async Task<IActionResult> Update(int id)
        {
            ProductionOperation productionOperation = await _service.GetByIdAsync(id);
            ProductionOperationDTO productionOperationDTO = _mapper.Map<ProductionOperationDTO>(productionOperation);
            return View(productionOperationDTO);
        }

        [HttpPost]
        public async Task<IActionResult> Update(ProductionOperationDTO operationDTO)
        {
            if (ModelState.IsValid)
            {

                ProductionOperation productionOperation = _mapper.Map<ProductionOperation>(operationDTO);
                await _service.UpdateAsync(productionOperation);
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        public async Task<IActionResult> Remove(int id)
        {
            ProductionOperation productionOperation = await _service.GetByIdAsync(id);
            await _service.RemoveAsync(productionOperation);

            return RedirectToAction(nameof(Index));
        }
    }
}

ProductOperation.Web/Controllers/StandartStoppingController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using ProductOperation.Core.DTOs;
using ProductOperation.Core.Models;
using ProductOperation.Core.Services;

namespace ProductOperation.Web.Controllers
{
    public class StandartStoppingController : Controller
    {
        private readonly IStandartStoppingService _service;
        private readonly IMapper _mapper;

        public StandartStoppingController(IStandartStoppingService service, IMapper mapper)
        {
            _service=service;
            _mapper=mapper;
        }

        public IActionResult Index()
        {
            List<StandartStopping> ss = _service.GetAll().ToList();
            List<StandartStoppingDto> standartStoppingDtos = _mapper.Map<List<StandartStoppingDto>>(ss);
            foreach (StandartStoppingDto standartStoppingDto in standartStoppingDtos)
            {
                TimeSpan dateTime = standartStoppingDto.EndTime-standartStoppingDto.StartTime;
                standartStoppingDto.TotalTime = dateTime;
            }
            return View(standartStoppingDtos);
        }
        public IActionResult Save()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Save(StandartStoppingDto standartStoppingDto)
        {
            if (ModelState.IsValid)
            {
                StandartStopping standart = _mapper.Map<StandartStopping>(standartStoppingDto);
                await _service.AddAsync(standart);

                return RedirectToAction(nameof(Index));
            }
            return View();
        }
        public async Task<IActionResult> Update(int id)
        {
            StandartStopping standartStopping = await _service.GetByIdAsync(id);
            StandartStoppingDto standartStoppingDto = _mapper.Map<StandartStoppingDto>(standartStopping);
            return View(standartStoppingDto);
        }
        [HttpPost]
        public async Task<IActionResult> Update(StandartStoppingDto standartStoppingDto)
        {
            if (ModelState.IsValid)
            {
                StandartStopping standart = _mapper.Map<StandartStopping>(standartStoppingDto);
                await _service.UpdateAsync(standart);
                return RedirectToAction(nameof(Index));
            }
            return View();
        }
        public async Task<IActionResult> Remove(int id)
        {
            StandartStopping standart = await _service.GetByIdAsync(id);
            await _service.RemoveAsync(standart);

            return RedirectToAction(nameof(Index));
        }
    }
}

ProductOperation.Web/Views/Home/Index.cshtml
@using ProductOperation.Core.DTOs
@{
    ViewData["Title"] = "AnaSayfa";
}

@model List<ProductionOperationDTO>


<div class=col-md-12>

    <form asp-action="Index" method="post" asp-controller="Home">

        <div class="form-group">
            <label>Tarih Seçiniz: </label>
            <input type="date" name="datetime" value="@DateTime.Parse("2020-05-23").ToString("yyyy-MM-dd")" />
            <input type="submit" value="Üretim Operasyonlarını Getir" class="btn-primary" />
        </div>
    </form>
</div>
<br/><br/>
@if (Model != null)
{
    if (Model.Count>0)
    {
        <div>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <td>No</td>
                        <td>Başlangıç</td>
                        <td>Bitiş</td>
                        <td>Toplam Süre(Saat)</td>
                        <td>Statü</td>
                        <td>Duruş Nedeni</td>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.No</td>
                            <td>@item.StartDateTime.ToString("MM/dd/yyyy HH:mm")</td>
                            <td>@item.EndDateTime.ToString("MM/dd/yyyy HH:mm")</td>
                            <td>@item.TotalTime.ToString(@"hh\:mm")</td>
                            <td>@(item.Status?"Üretim":"Duruş")</td>
                            <td>@item.StoppingReason</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    }
    else
    {
        <p> "SEÇTİĞİNİZ @ViewBag.Message İÇİN KAYIT BULUNAMADI"</p>
    }
}

ProductOperation.Web/Views/ProductionOperation/Index.cshtml
@using ProductOperation.Core.DTOs
@{
    ViewData["Title"] = "Index";
}
@model List<ProductionOperationDTO>

<div class=col-md-12>

    <form asp-action="Index" method="post" asp-controller="ProductionOperation">

        <div class="form-group">
            <label>Tarih Seçiniz: </label>
            <input type="date" name="datetime" value="@DateTime.Parse("2020-05-23").ToString("yyyy-MM-dd")" />
            <input type="submit" value="Üretim Operasyonlarını Getir" class="btn-primary" />
        </div>
    </form>
</div>

<br/><br/>
@if (Model != null)
{
    if (Model.Count > 0)
    {
        <div>
            <a class="btn btn-primary" asp-controller="ProductionOperation" asp-action="Save">Yeni Ekle</a><br/>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <td>No</td>
                        <td>Başlangıç</td>
                        <td>Bitiş</td>
                        <td>Toplam Süre(Saat)</td>
                        <td>Statü</td>
                        <td>Duruş Nedeni</td>
                        <td>Düzenle</td>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.No</td>
                            <td>@item.StartDateTime.ToString("MM/dd/yyyy HH:mm")</td>
                            <td>@item.EndDateTime.ToString("MM/dd/yyyy HH:mm")</td>
                            <td>@item.TotalTime.ToString(@"hh\:mm")</td>
                            <td>@(item.Status ? "Üretim" : "Duruş")</td>
                            <td>@item.StoppingReason</td>
                            <td>
                                <a class="btn btn-warning" asp-controller="ProductionOperation" asp-action="Update" asp-route-id="@item.Id">Düzenle</a>
                                <a class="btn btn-danger" asp-controller="ProductionOperation" asp-action="Remove" asp-route-id="@item.Id">Sil</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    }
}

ProductOperation.Web/Views/ProductionOperation/Save.cshtml
@using ProductOperation.Core.DTOs

@{
    ViewData["Title"] = "Save";
}
@model ProductionOperationDTO

<h1>Üretim Operasyonu Ekle</h1>
<div class="row">

    <div class=col-md-6>

        <form asp-action="Save" method="post" asp-controller="ProductionOperation">

            <div class="form-group">
                <label asp-for="No">No</label>
                <input asp-for="No" class="form-control" />
                <span asp-validation-for="No" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDateTime">Başlangıç</label>
                <input asp-for="StartDateTime" class="form-control" ID="StartDateTime"/>
                <span asp-validation-for="StartDateTime" class="text-danger" ></span>
            </div>

            <div class="form-group">
                <label asp-for="EndDateTime">Bitiş</label>
                <input asp-for="EndDateTime" class="form-control" ID="EndDateTime"/>
                <span asp-validation-for="EndDateTime" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Status">Statü</label>
                <select class="form-control" asp-for="Status" id="Status">
                    <option value="False">Duruş</option>
                    <option value="True">Üretim</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="StoppingReason">Duruş Nedeni</label>
                <input asp-for="StoppingReason" class="form-control" />
                <span asp-validation-for="StoppingReason" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn-primary" />
            </div>
        </form>



    </div>


</div>

ProductOperation.Web/Views/ProductionOperation/Update.cshtml
@using ProductOperation.Core.DTOs

@{
    ViewData["Title"] = "Update";
}
@model ProductionOperationDTO

<h1>Üretim Operasyonunu Düzenle</h1>
<div class="row">

    <div class=col-md-6>

        <form asp-action="Update" method="post" asp-controller="ProductionOperation">
            <input type="hidden" asp-for="Id" />

            <div class="form-group">
                <label asp-for="No">No</label>
                <input asp-for="No" class="form-control" />
                <span asp-validation-for="No" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDateTime">Başlangıç</label>
                <input asp-for="StartDateTime" class="form-control" />
                <span asp-validation-for="StartDateTime" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="EndDateTime">Bitiş</label>
                <input asp-for="EndDateTime" class="form-control" />
                <span asp-validation-for="EndDateTime" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Status">Statü</label>
                <select class="form-control" asp-for="Status" id="Status">
                    <option value="False">Duruş</option>
                    <option value="True">Üretim</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="StoppingReason">Duruş Nedeni</label>
                <input asp-for="StoppingReason" class="form-control" />
                <span asp-validation-for="StoppingReason" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Güncelle" class="btn-primary" />
            </div>
        </form>
    </div>
</div>

ProductOperation.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProductOperation.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProductOperation.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Ana Sayfa</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Ana Sayfa</a>
                            </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ProductionOperation" asp-action="Index">Üretim Operasyonları</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="StandartStopping" asp-action="Index">Standart Duruşlar</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ProductOperation.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ProductOperation.Web/Views/StandartStopping/Index.cshtml
@using ProductOperation.Core.DTOs

@{
    ViewData["Title"] = "Index";
}
@model List<StandartStoppingDto>
<h1>Standart Duruşlar</h1>
<a class="btn btn-primary" asp-controller="StandartStopping" asp-action="Save">Yeni Ekle</a>
<table class="table table-striped">
    <thead>
        <tr>
            
            <td>Başlangıç</td>
            <td>Bitiş</td>
            <td>Duruş Nedeni</td>
            <td>Düzenle</td>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.StartTime.ToString(@"hh\:mm")</td>
                <td>@item.EndTime.ToString(@"hh\:mm")</td>
                <td>@item.StoppingReason</td>
                <td>
                    <a class="btn btn-warning" asp-controller="StandartStopping" asp-action="Update" asp-route-id="@item.Id">Düzenle</a>
                    <a class="btn btn-danger" asp-controller="StandartStopping" asp-action="Remove" asp-route-id="@item.Id">Sil</a>
                </td>
            </tr>
        }
    </tbody>
</table>

ProductOperation.Web/Views/StandartStopping/Save.cshtml
@using ProductOperation.Core.DTOs

@{
    ViewData["Title"] = "Ekle";
}
@model StandartStoppingDto
<h1>Yeni Standart Duruş Ekle</h1>
<div class="row">
    <div class=col-md-6>
        <form asp-action="Save" method="post" asp-controller="StandartStopping">
            <div class="form-group">
                <label asp-for="StartTime">Başlangıç</label>
                <input asp-for="StartTime" class="form-control" />
                <span asp-validation-for="StartTime" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="EndTime">Bitiş</label>
                <input asp-for="EndTime" class="form-control" />
                <span asp-validation-for="EndTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StoppingReason">Duruş Nedeni</label>
                <input asp-for="StoppingReason" class="form-control" />
                <span asp-validation-for="StoppingReason" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn-primary" />
            </div>
        </form>
    </div>
</div>

ProductOperation.Web/Views/StandartStopping/Update.cshtml
@using ProductOperation.Core.DTOs

@{
    ViewData["Title"] = "Update";
}
@model StandartStoppingDto
<h1>Yeni Standart Duruşları Düzenle</h1>
<div class="row">
    <div class=col-md-6>
        <form asp-action="Update" method="post" asp-controller="StandartStopping">
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="StartTime">Başlangıç</label>
                <input asp-for="StartTime" class="form-control" />
                <span asp-validation-for="StartTime" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="EndTime">Bitiş</label>
                <input asp-for="EndTime" class="form-control" />
                <span asp-validation-for="EndTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StoppingReason">Duruş Nedeni</label>
                <input asp-for="StoppingReason" class="form-control" />
                <span asp-validation-for="StoppingReason" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Güncelle" class="btn-primary" />
            </div>
        </form>
    </div>
</div>